CREATE TABLE [dbo].[GzConfigurations] (
    [Id]                        INT  IDENTITY (1, 1) NOT NULL,
    [LOCK_IN_NUM_DAYS]          INT  NOT NULL,
    [COMMISSION_PCNT]           REAL NOT NULL,
    [FUND_FEE_PCNT]             REAL NOT NULL,
    [CREDIT_LOSS_PCNT]          REAL NOT NULL,
    [FIRST_PORTFOLIO_RISK_VAL]  INT  DEFAULT ((3)) NOT NULL,
    [CONSERVATIVE_RISK_ROI]     REAL DEFAULT ((3.5)) NOT NULL,
    [MEDIUM_RISK_ROI]           REAL DEFAULT ((5)) NOT NULL,
    [AGGRESSIVE_RISK_ROI]       REAL DEFAULT ((7.5)) NOT NULL,
    [EARLY_WITHDRAWAL_FEE_PCNT] INT  DEFAULT ((25)) NOT NULL,
    [HURDLE_FEE_PCNT]           INT  DEFAULT ((25)) NOT NULL,
    [HURDLE_TRIGGER_GAIN_PCNT]  INT  DEFAULT ((10)) NOT NULL,
    CONSTRAINT [PK_dbo.GzConfigurations] PRIMARY KEY CLUSTERED ([Id] ASC)
);







