// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../Gm2Gz/packages/ExcelProvider.0.8.0/lib/Excel.dll"
#r "../../Gm2Gz/packages/ExcelProvider.0.8.0/lib/ExcelProvider.dll"
#r "../../Gm2Gz/packages/FSharp.Data.2.3.2/lib/net40/FSharp.Data.dll"
#r "../../Gm2Gz/packages/FSharp.Data.TypeProviders.5.0.0.2/lib/net40/FSharp.Data.TypeProviders.dll"
#r "../../Gm2Gz/packages/ExcelProvider.0.8.0/lib/ICSharpCode.SharpZipLib.dll"
#r "../../Gm2Gz/packages/NLog.4.3.9/lib/net45/NLog.dll"
#r "System.Core.dll"
#r "System.Data.dll"
#r "System.Data.Linq.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "System.Transactions.dll"
#r "System.Xml.Linq.dll"