// <auto-generated />
namespace gzWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renames_at_carousel_entry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renames_at_carousel_entry));
        
        string IMigrationMetadata.Id
        {
            get { return "201609151011375_renames_at_carousel_entry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
