// <auto-generated />
namespace gzWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Consolidate_SoldVintage_InvBalance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Consolidate_SoldVintage_InvBalance));
        
        string IMigrationMetadata.Id
        {
            get { return "201607041000197_Consolidate_SoldVintage_InvBalance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
