// <auto-generated />
namespace gzWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Many2ManyPortFund : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Many2ManyPortFund));
        
        string IMigrationMetadata.Id
        {
            get { return "201601150911269_Many2Many PortFund"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
