// <auto-generated />
namespace gzWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_DynamicPages_From_And_To_To_DateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_DynamicPages_From_And_To_To_DateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201606281327185_Change_DynamicPages_From_And_To_To_DateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
