// <auto-generated />
namespace gzWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_IsMobile_Field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsMobile_Field));
        
        string IMigrationMetadata.Id
        {
            get { return "201610260908570_Add_IsMobile_Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
