// <auto-generated />
namespace gzWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CarouselEntry_SoftDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarouselEntry_SoftDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201610121356178_CarouselEntry_SoftDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
