// <auto-generated />
namespace gzWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GetVintages_ShowAllMonths : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetVintages_ShowAllMonths));
        
        string IMigrationMetadata.Id
        {
            get { return "201704250855218_GetVintages_ShowAllMonths"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
