// <auto-generated />
namespace gzWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CashDeposits_XReportDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CashDeposits_XReportDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201803101802259_CashDeposits_XReportDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
